"""updating

Revision ID: 2b60fb8cef88
Revises: 2a02ac1b8438
Create Date: 2023-10-27 16:02:31.149890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b60fb8cef88'
down_revision = '2a02ac1b8438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
