"""adding languages

Revision ID: 43e6d788ae5f
Revises: a9b3ba9d48bd
Create Date: 2023-10-27 15:27:15.069226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e6d788ae5f'
down_revision = 'a9b3ba9d48bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('code', sa.String(length=30), nullable=False))
    op.add_column('languages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'stories', 'languages', ['language'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('languages', 'deleted_at')
    op.drop_column('languages', 'code')
    # ### end Alembic commands ###
