"""relation edit

Revision ID: 63b9df3a73b9
Revises: 2b60fb8cef88
Create Date: 2023-10-30 16:41:33.767284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b9df3a73b9'
down_revision = '2b60fb8cef88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
