"""declarative class edit

Revision ID: 6caac1e22bc5
Revises: be2d23e8307e
Create Date: 2023-10-30 16:59:32.898746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6caac1e22bc5'
down_revision = 'be2d23e8307e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
