"""declarative class edit

Revision ID: 732c3f884f24
Revises: 01a5d0142d6f
Create Date: 2023-10-30 17:38:52.046422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '732c3f884f24'
down_revision = '01a5d0142d6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('languages', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
