"""updating

Revision ID: 79a46c056f02
Revises: 1c07ad0652b8
Create Date: 2023-10-27 15:58:40.945315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79a46c056f02'
down_revision = '1c07ad0652b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('language', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'languages', ['language'], ['id'])
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'language')
    # ### end Alembic commands ###
