"""updating table

Revision ID: 820249552877
Revises: 
Create Date: 2023-10-27 14:38:05.706796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820249552877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
