"""declarative class edit

Revision ID: 8d7a3ec8cf16
Revises: 732c3f884f24
Create Date: 2023-10-30 17:40:22.410333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7a3ec8cf16'
down_revision = '732c3f884f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
