"""declarative class edit

Revision ID: 954cd0904501
Revises: 8d7a3ec8cf16
Create Date: 2023-10-30 18:00:04.829862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '954cd0904501'
down_revision = '8d7a3ec8cf16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('stories', 'status_flag',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.alter_column('stories', 'schedule',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stories', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stories', 'keyword_old',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('stories', 'keyword',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('stories', 'youtube_id',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('stories', 'description_1',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'description_1',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('stories', 'youtube_id',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('stories', 'keyword',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('stories', 'keyword_old',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('stories', 'deleted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('stories', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('stories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('stories', 'schedule',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('stories', 'status_flag',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
