"""declarative class edit

Revision ID: 9a4ab5a76897
Revises: 954cd0904501
Create Date: 2023-10-30 18:16:35.755635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4ab5a76897'
down_revision = '954cd0904501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
