"""declarative class edit

Revision ID: a97fb0b65765
Revises: fe52901f1e24
Create Date: 2023-10-30 17:03:15.025017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97fb0b65765'
down_revision = 'fe52901f1e24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
