"""updating categories

Revision ID: a9b3ba9d48bd
Revises: 820249552877
Create Date: 2023-10-27 14:47:54.057607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9b3ba9d48bd'
down_revision = '820249552877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status_flag', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('stories', 'category',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stories', 'language',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('stories', 'category',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'status_flag')
    # ### end Alembic commands ###
