"""declarative class edit

Revision ID: be2d23e8307e
Revises: 63b9df3a73b9
Create Date: 2023-10-30 16:58:31.669137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2d23e8307e'
down_revision = '63b9df3a73b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
