"""declarative class edit

Revision ID: f53972d066c2
Revises: 9a4ab5a76897
Create Date: 2023-10-30 18:16:55.754970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53972d066c2'
down_revision = '9a4ab5a76897'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
