"""declarative class edit

Revision ID: fe52901f1e24
Revises: 6caac1e22bc5
Create Date: 2023-10-30 17:02:51.066262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe52901f1e24'
down_revision = '6caac1e22bc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
